apiVersion: v1
kind: Pod
metadata:
  name: mypod2
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
    - name: mytomcat1
      image: tomcat
      ports:
        - containerPort: 8088
